[package]
name = "words"
version = "0.1.0"
authors = ["Yevhen Blotskyi <yebl@boozt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
